version: "3.4"
volumes:
  shared-volume:
services:
  zoo1:
    container_name: zoo1
    image: zookeeper:${ZOOKEEPER_VERSION}
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: ${ZOO_SERVERS}

  zoo2:
    container_name: zoo2
    image: zookeeper:${ZOOKEEPER_VERSION}
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: ${ZOO_SERVERS}

  zoo3:
    container_name: zoo3
    image: zookeeper:${ZOOKEEPER_VERSION}
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: ${ZOO_SERVERS}

  swoole:
    container_name: swoole
    restart: always
    hostname: swoole
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      IMI_ZOOKEEPER_HOST: zoo1:2181
      PHPX_VERSION: ${PHPX_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null
